import "dotenv/config";
const {
  NODE_ENV,
  PORT,
  MONGODB_URI_AUTH,
  MONGODB_URI_CPE,
  MONGODB_URI_AUTH_DEV,
  MONGODB_URI_CPE_DEV,
  REDIS_URL,
  ZABBIX_HOST,
  ZABBIX_USERNAME,
  ZABBIX_PASSWORD,
  TELEGRAM_TOKEN,
  TELEGRAM_CHAT_ID,
  JWT_ACCESS_SECRET,
  JWT_ACCESS_EXPIRESIN,
  JWT_REFRESH_SECRET,
  JWT_REFRESH_EXPIRESIN,
} = process.env;

export default {
//   accessTokenPrivateKey: JWT_ACCESS_SECRET,
//   refreshTokenPrivateKey: JWT_REFRESH_SECRET,
};
